# Generated by Django 5.1.4 on 2025-01-05 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_musiclink_musiccontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='is_out_of_stack',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='musiccontent',
            name='title',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
