# Generated by Django 5.1.4 on 2025-01-13 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_discount_price_product_is_out_of_stack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Enter a title for the audio file sample', max_length=255, null=True)),
                ('audio_file', models.FileField(help_text='Upload an audio file', upload_to='audio_samples/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Note: Don't forget to update Stripe Price.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
